
#ifndef BOOK_MANAGEMENT_GUARD__H 
#define BOOK_MANAGEMENT_GUARD__H

#include <stdio.h>
#include <stdlib.h>
#include<windows.h>
#include <string.h>
/*You can extend the structs (Book and BookArray) defined in this head file;
  However, you may not change the function prototypes. 
  You are also free to add additional head files and data structures as needed. 
*/


typedef struct _Book {
	    unsigned int id; //Book ID
		char *title; //book title
		char *authors; //comma separated list of authors
		unsigned int year; // year of publication
		unsigned int copies; //number of copies the library has
		struct _Book *nextbook;//定义指针域 
}Book;

typedef struct _BookArray {
	 Book* array; // pointer to array (or linked list) of struct Book.
	 unsigned int length; // number of elements in the (Book*) array 
}BookArray;

typedef Book *pbook;

pbook bookhead = NULL;//创建头指针，初始值为NULL 

int store_books(FILE *file);
int load_books(FILE *file);
pbook Last_books();
int add_book(Book book);
int remove_book(Book book);
BookArray find_book_by_title (const char *title);
BookArray find_book_by_author (const char *author);
BookArray find_book_by_year (unsigned int year);
int Add_book();
int Remove_book();

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file)//已经给了特定文件的指针了 
{
	int a;
	pbook sbook = bookhead ,lastbook = NULL;
	lastbook = Last_books();
	if(lastbook=NULL){
		lastbook = sbook;
	} 
	file=fopen("bookfile","ab+");   //以追加的方式打开名字为mybook的二进制文件 
	if(file==NULL)
	{
		printf("file can't be opened");
		return 1; 
	}
	if (sbook==NULL){
		return 1;//链表还为空，没有书籍需要存入文件 
	}
	while(sbook!=NULL){
		while(1){
			if(sbook!=lastbook){ //将已经存储的书筛除 
				sbook=sbook->nextbook;
			}
			else{
				sbook=sbook->nextbook;
				break;
			}
		}
		if(sbook==NULL){
			return 1;//没有需要存入的书 
		}
		a=fwrite(sbook,sizeof(struct _Book),1,file);//将链表中的内容内容存入file所指向的文件中
		if(a!=1)   
		{
			printf("An error occurred while writing to the file");
			return 1;
		}
		sbook = sbook->nextbook; 	
	}
	fclose(file);    //关闭文件
	return 0;	
} 
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
	file=fopen("bookfile","ab+");  //打开文件
	pbook bookpa = NULL, bookpb = NULL, bookpc = NULL;
	if(file==NULL)
	{
		printf("the file can not be opened successfully\n");
		return 1;
	}
	while(!feof(file))        //判断读写标志是否移到文件末尾 
	{
	    bookpa=(pbook)malloc(sizeof(Book)); //用malloc在内存申请一段空间 
	   fread(bookpa,sizeof(struct _Book),1,file);     //将file所指向文件的内容传递给bookpa 
	   if(bookhead==NULL)
	   {
	      bookhead=bookpa;
	      bookpb=bookpa;
	    }
	    else             //建立链表 
	    {
	    	bookpc=bookpb;
	    	bookpb->nextbook=bookpa;
	    	bookpb=bookpa;
		}
    }
    if(bookpc!=NULL)  	//文件里没有数据 
       bookpc->nextbook=NULL;
    else
       bookhead=NULL;
    fclose(file);    //关闭文件
	return 0; 
}

pbook Last_books(){
	FILE *file1;
	file1=fopen("bookfile","ab+");  //打开文件
	pbook bookpa = NULL, bookpb = NULL, bookpc = NULL, bookpd=NULL;
	bookpd=bookhead;
	if(file1==NULL)
	{
		printf("the file can not be opened successfully\n");
	}
	while(!feof(file1))        //判断读写标志是否移到文件末尾 
	{
	    bookpa=(pbook)malloc(sizeof(Book)); //用malloc在内存申请一段空间 
	   fread(bookpa,sizeof(struct _Book),1,file1);     //将file所指向文件的内容传递给bookpa 
	   if(bookpd==NULL)
	   {
	      bookpd=bookpa;
	      bookpb=bookpa;
	    }
	    else             //建立链表 
	    {
	    	bookpc=bookpb;
	    	bookpb->nextbook=bookpa;
	    	bookpb=bookpa;
		}
    }
    if(bookpc!=NULL)  	 
       bookpc->nextbook=NULL;
    else			  //文件里没有数据 
       bookpd=NULL;
    fclose(file1);    //关闭文件
	return bookpc; 
}

//添加新书籍的ID，作者等等 
int Add_book()
{
	do
	{
		pbook padd = NULL;
		FILE *file;    //指向文件的指针 
		int s,f;
		padd=(pbook)malloc(sizeof(Book));//申请内存空间
		if(padd == NULL){			//如果申请内存失败，则添加book失败，返回1 
			printf("memory allocation failed\n");
			return 1;
		}
		add_book(*padd);
		//添加图书信息
		printf(" Please input BOOK id ");    
		scanf("%s",&padd->id);
		printf(" Please input BOOK title ");
		scanf("%s",&padd->title);
		printf("Please input BOOK authors");
		scanf("%s",&padd->authors);
		printf("Please input Year of publication");
		scanf("%s",&padd->year);
		printf("Please input the number of copies of the book\n");
		scanf("%s",&padd->copies);
		padd->nextbook = NULL;//新增的节点位于链表末端，所以为null 
		system("pause");
		printf("|                                              |");
		printf("| Saved successfully. Do you want to continue  |");
		printf("| 1.YES                                    2.NO|\n"); 
		scanf("%d",&s);
		do{
			if(s=='1')
			{
				break;
			}	 
			else if(s=='2')
			{
				return 0;
			}			
		 }while(1);  
	}while(1);
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book)
{
	pbook bookpr = bookhead;
	if(bookhead == NULL){ //如果头指针是NULL,说明可以从头添加节点 
		bookhead = &book;
	}else{
		while(bookpr->nextbook!= NULL){
				bookpr = bookpr->nextbook;
		}
		bookpr->nextbook = &book;
	}
	return 0; 
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book);
//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title (const char *title);

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author (const char *author);

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year (unsigned int year);


#endif
